### ISSUE TITLE
The endpoint is fqdn:9000 ?

### ISSUE THREAD

**Issue by kgnfth** [sakkiii/minio-docker-letsencrypt-deploy#7]
this is my env
```
MINIO_REGION_NAME=eu-east-1
FQDN=minio.redacted.fun
```
So we use https://minio.redacted.fun:9000 as the endpoint (api) ?

Also it would be cool if u enable github "Discussions"

**Comment by sakkiii** [comment]
@kgnfth yes https://${FQDN}:9000 will be MinIO API endpoint and https://${FQDN} will be MinIO console.

> Also it would be cool if u enable github "Discussions"
Yes Sure.

**Comment by kgnfth** [comment]
> @kgnfth yes https://${FQDN}:9000 will be MinIO API endpoint and https://${FQDN} will be MinIO console.
> 
> > Also it would be cool if u enable github "Discussions"
> > Yes Sure.

Thx
