### ISSUE TITLE
ERROR Invalid MINIO_BROWSER_REDIRECT_URL value in environment variable

### ISSUE THREAD

**Issue by kgnfth** [sakkiii/minio-docker-letsencrypt-deploy#8]
As it states in the readme for FQDN `a space separated list of domains for which you want to generate certificates`
i set my fqdn like this
`FQDN=minio.redacted.fun xbackbone.minio.redacted.fun`

But i get this error
```{r, include=FALSE}
minio1_1   | ERROR Invalid MINIO_BROWSER_REDIRECT_URL value in environment variable: parse "https://minio.redacted.fun xbackbone.minio.redacted.fun": invalid character " " in host name
```

**Comment by sakkiii** [comment]
MINIO_BROWSER_REDIRECT_URL - https://github.com/sakkiii/minio-docker-letsencrypt-deploy/blob/main/docker-compose.yaml#L20
FQDN is a domain endpoint where MinIO will be hosted with letsencrypt SSL certificates. As of now only one domain will be supported.  I have done fix in README.

It will be great if we can have support for multiple domains like example.com and www.example.com. I will add that in future roadmap and will give it a thought.

**Comment by kgnfth** [comment]
> MINIO_BROWSER_REDIRECT_URL - https://github.com/sakkiii/minio-docker-letsencrypt-deploy/blob/main/docker-compose.yaml#L20
> FQDN is a domain endpoint where MinIO will be hosted with letsencrypt SSL certificates. As of now only one domain will be supported. I have done fix in README.
> 
> It will be great if we can have support for multiple domains like example.com and [www.example.com](http://www.example.com). I will add that in future roadmap and will give it a thought.

Thank you. 
Also i replaced certbot with https://github.com/go-acme/lego 

i use it like this and it work better for me
i can now use `https://s3.domain.com` for the console api without port, because i got trouble with certbot for using `-d paramater`
```
  lego:
    image: goacme/lego
    env_file:
      - ./.env
    command: >
      --email ${CERTBOT_EMAIL}
      --dns pdns
      --domains ${CONSOLE_FQDN}
      --domains ${API_FQDN}
      --domains ${PORTAINER_FQDN}
      --path /lego
      --accept-tos
      run
    volumes:
      - lego-accounts:/lego/accounts
      - lego-certificates:/lego
```

it has better integration for custom dns providers
here is the source of the changes i made for my usecase
https://github.com/kgnfth/minio-docker-certbot
